# Generated by Django 6.0.1 on 2026-02-13 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('job_hunt', '0001_initial'), ('job_hunt', '0002_pastevents'), ('job_hunt', '0003_alter_pastevents_date')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobHunt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job_hunt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('distance_from_home', models.FloatField(blank=True, null=True)),
                ('min_salary', models.IntegerField(blank=True, null=True)),
                ('max_salary', models.IntegerField(blank=True, null=True)),
                ('is_remote_only', models.BooleanField(default=False)),
                ('is_in_office_only', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('job_hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='job_hunt.jobhunt')),
            ],
            options={
                'db_table': 'job_posting',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Bookmarked', 'Bookmarked'), ('Applied', 'Applied'), ('PhoneScreen', 'Phonescreen'), ('Interview', 'Interview'), ('TakeHome', 'Takehome'), ('FinalRound', 'Finalround'), ('Offer', 'Offer'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Bookmarked', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job_hunt.jobposting')),
            ],
            options={
                'db_table': 'job_application',
                'ordering': ['-date_applied'],
            },
        ),
        migrations.CreateModel(
            name='PastEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'past_events',
                'ordering': ['-date'],
            },
        ),
    ]
